fix: #568 Terraform destroy fails when state is empty
terraform-aws-modules/terraform-aws-eks pull request #1020
Opened 2020-09-22 22:49 UTC by ageekymonk

# Terraform destroy fails when state is empty

## Description

The terraform destroy fails on any incomplete run because there is reference of name everywhere. Replacing the name with user provided one. Fixes #568 

### Checklist

- [ ] CI tests are passing
- [x ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

2020-09-23 22:57 UTC, ageekymonk commented
I am not sure why Lint/Docs is failing. Please let me know what should i do to fix it.

2020-10-04 19:15 UTC, barryib commented
> I am not sure why Lint/Docs is failing. Please let me know what should i do to fix it.

You need to rebase your branch from master

2020-10-04 19:24 UTC, barryib requested changes
Thanks @ageekymonk for your PR. Please can you use splat syntax instead of ternary operation.

2020-10-04 19:24 UTC, barryib commented on local.tf
> +    endpoint                          = length(aws_eks_cluster.this) > 0 ? aws_eks_cluster.this[0].endpoint : ""
Please use the splat syntax instead.

`coalescelist(aws_eks_cluster.this[*]. endpoint, [""])[0]` This will return `""` if the state is empty.

2020-10-04 19:24 UTC, barryib commented on local.tf
> +    aws_authenticator_command_args    = length(var.kubeconfig_aws_authenticator_command_args) > 0 ? var.kubeconfig_aws_authenticator_command_args : ["token", "-i", var.cluster_name]
`coalescelist(aws_eks_cluster.this[*].name, [""])[0]` This is true for all your change.

2020-10-04 19:24 UTC, barryib commented on workers.tf
> +        var.cluster_name,
Please use the splat syntax instead : `coalescelist(aws_eks_cluster.this[*].name, [""])[0]` This is true for all your change.

2020-10-06 20:19 UTC, barryib commented
Thanks @ageekymonk for your work. I'm closing this in favor of https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1041

2020-10-06 20:19 UTC, closed without merging