Remove dependency on deprecated hashicorp/template
terraform-aws-modules/terraform-aws-eks pull request #1297
Opened 2021-04-12 22:20 UTC by dmsalomon

# PR o'clock

## Description

hashicorp/template is deprecated, and the templatefile function should be used instead. In particular, this is problem on new Apple silicon Macs, since the hashicorp/template provider is not implemented (and I don't ever will be) for darwin_arm64. See #1294

I have replaced the "template_file" data sources with local variables that store the outputs to function calls using `template`. There is actually very little that has changed since the resource arguments map cleanly to the function arguments. I had to use an explicit for loop to render the templates for every node, instead of using the `count` meta-argument.

I'm relatively new to Terraform, so all critiques are appreciated.

### Checklist

- [ ] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

2021-04-19 21:14 UTC, barryib commented
This break some use cases. For the record, see https://github.com/hashicorp/terraform/pull/24978

2021-05-04 21:16 UTC, barryib commented
@dmsalomon Thanks for working on this. Can you please upgrade your branch ?

2021-05-04 21:56 UTC, dmsalomon commented
@barryib Thanks for taking a look at this, I just upgraded the branch.

2021-05-05 20:57 UTC, barryib requested changes

2021-05-05 20:57 UTC, barryib commented on versions.tf
> -    template   = ">= 2.1"
Can you please also remove the template provider from required providers in [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples).

2021-05-17 08:17 UTC, barryib approved these changes

2021-05-17 08:25 UTC, merged

2021-05-17 08:26 UTC, barryib commented
Thanks @dmsalomon for your contribution.

2021-05-17 20:25 UTC, barryib commented
This now shipped in [v16.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v16.0.0)