Add variable to allow configuring the wait for cluster timeout.
terraform-aws-modules/terraform-aws-eks pull request #1420
Opened 2021-06-01 19:45 UTC by SNA-rh

# PR o'clock

## Description

During #1359 a default timeout of 300 seconds was set for this.  We create hundreds of clusters a day and have seen many clusters take longer than 300 seconds.   Our team previously used the `wait_for_cluster_cmd` (*NOTE*: This is no longer used) set to wait 600 seconds.  Sometimes, even 5 minutes isn't even enough.  This PR will make this configurable, so our clusters are more likely to come up in time.

This fixes #1395 

### Checklist

- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

2021-06-01 20:19 UTC, barryib reviewed
Thanks for working on this. Just variable rewording, otherwise it's LGTM.

2021-06-01 20:19 UTC, barryib commented on variables.tf
> +variable "wait_for_cluster_create_timeout" {
```suggestion
variable "wait_for_cluster_timeout" {
```

2021-06-01 20:47 UTC, barryib requested changes
On last thing to clarify please ^^.

2021-06-01 20:47 UTC, barryib commented on variables.tf
> +  description = "A timeout of 5mn when waiting for cluster to be available."
Can you please specify that the timeout is in second ?

2021-06-01 20:47 UTC, barryib commented on variables.tf
> +  default     = 300
Shouldn't we add `type = number` ?

2021-06-01 21:01 UTC, SNA-rh commented
@barryib I updated the code. Let me know if it looks better now.

I was not sure of the process, so I resolved the comment issues myself.  I hope that's OK.

2021-06-01 21:04 UTC, barryib approved these changes

2021-06-01 21:10 UTC, merged

2021-06-01 21:10 UTC, barryib commented
Nice. Thanks @SNA-rh for you contribution.

2021-06-09 17:58 UTC, jonDowdle commented
@barryib We're real excited to use this. Any idea when the next release gets cut that'd include it?

2021-06-09 18:04 UTC, barryib commented
Just released it in [v17.1.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v17.1.0)