Update UPGRADE-19.0.md
terraform-aws-modules/terraform-aws-eks pull request #2445
Opened 2023-02-02 17:57 UTC by felipewnp

Grammar correction.

2023-02-04 14:12 UTC, bryantbiggs commented on docs/UPGRADE-19.0.md
> -### Self-Managed Node Group IAM Role
This is the correct form https://docs.aws.amazon.com/eks/latest/userguide/worker.html

2023-02-04 14:13 UTC, bryantbiggs requested changes
The form `self-managed` should stay as is

2023-02-09 13:42 UTC, bryantbiggs approved these changes

2023-02-09 13:42 UTC, merged

2023-02-15 21:03 UTC, antonbabenko commented
This PR is included in version 19.8.0 :tada: