Allow passing in null to disable instance refreshes
terraform-aws-modules/terraform-aws-eks pull request #3131
Opened 2024-08-21 17:44 UTC by ramseymcgrathfd

## Description
Allows a user to pass in `{}` for the instance_refresh argument and stop the dynamic block from creating the refresh. Currently you cannot disable an instance refresh without a separate module call.

## Motivation and Context
A user may want to only refresh a set of nodes and not enable it for every node group in the cluster. This adds support for that workflow by handling an empty config safely.

## Breaking Changes
No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

Have deployed this code to local clusters to confirm behavior is as expected.

- [x] I have executed `pre-commit run -a` on my pull request

2024-08-21 18:13 UTC, bryantbiggs requested changes
this does not appear to be a valid change

2024-08-21 18:32 UTC, ramseymcgrathfd commented on modules/self-managed-node-group/main.tf
> +    for_each = alltrue([
Correct but you can't pass this into a module for example
```
  instance_refresh = var.instance_refresh ? {
    preferences = {
        min_healthy_percentage = var.instance_maintenance_policy.min_healthy_percentage
      }
      strategy = "Rolling"
    } : {}
    ```
    It'll always return
    ```
    
│ Error: Inconsistent conditional result types
│ 
│   on main.tf line 177, in module "self_managed_node_group":
│  177:   instance_refresh = var.instance_refresh ? {
│  178:     preferences = {
│  179:         min_healthy_percentage = var.instance_maintenance_policy.min_healthy_percentage
│  180:       }
│  181:       strategy = "Rolling"
│  182:     } : {}
│     ├────────────────
│     │ var.instance_maintenance_policy.min_healthy_percentage is a number
│     │ var.instance_refresh is a bool
│ 
│ The true and false result expressions must have consistent types. The 'true' value includes object attribute "preferences", which is absent in the 'false'
│ value.
╵
```

2024-08-21 18:36 UTC, ramseymcgrathfd commented on modules/self-managed-node-group/main.tf
> +    for_each = alltrue([
The length() check also blocks null values

2024-08-21 18:43 UTC, ramseymcgrathfd commented
> this does not appear to be a valid change

Updated convo above

2024-08-22 21:20 UTC, ramseymcgrathfd commented
@bryantbiggs added issue explaining the reasoning

2024-08-23 13:45 UTC, bryantbiggs commented on modules/self-managed-node-group/main.tf
> +    for_each = alltrue([
why would you want to pass in something like this?

```hcl
instance_refresh = var.instance_refresh ? {
    preferences = {
        min_healthy_percentage = var.instance_maintenance_policy.min_healthy_percentage
      }
      strategy = "Rolling"
    } : {}
```

2024-08-23 18:39 UTC, ramseymcgrathfd commented
This behavior is intended, closing

2024-08-23 18:39 UTC, closed without merging